% Generated by JCC02M
	LOC  Data_Segment
	GREG @
	LOC  #100
Main	IS   @
	LOC  Main

% decl: int s -> $2
% decl: int i -> $3
	SET $200,0
	SET $2,$200
	SET $201,1
	SET $3,$201
L0	SET $202,100
	CMP $203,$3,$202
	BP  $203,L1
	ADD $204,$2,$3
	SET $2,$204
	SET $205,1
	ADD $206,$3,$205
	SET $3,$206
	JMP L0

L1	TRAP 0,Halt,0
