#include "codegen.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ---- 内部状态 ---- */
static SymTab   *symtab;
static int       label_seq;
static int       temp_seq;
static int       pending_label;   /* >=0 表示有待输出的标签 */
static BinOpType last_cmp_op;

#define TEMP_BASE 200

static int new_label(void) { return label_seq++; }
static int alloc_temp(void) { return TEMP_BASE + temp_seq++; }

/* ---- 标签机制 ---- */

/* 标记：下一条指令前需要先输出此标签 */
static void set_label(int id) {
    pending_label = id;
}

/* 输出指令前缀：有标签则输出标签，否则输出缩进 */
static void emit_prefix(void) {
    if (pending_label >= 0) {
        printf("L%d\t", pending_label);
        pending_label = -1;
    } else {
        printf("\t");
    }
}

/* ---- 前向声明 ---- */
static void gen_statement(ASTNode *node);
static int  gen_expr(ASTNode *node);

/* ---- 程序入口 ---- */
void codegen(ASTNode *program, SymTab *st) {
    symtab       = st;
    label_seq    = 0;
    temp_seq     = 0;
    pending_label = -1;

    /* MMIX 文件头 */
    printf("%% Generated by JCC02M\n");
    printf("\tLOC  Data_Segment\n");
    printf("\tGREG @\n");
    printf("\tLOC  #100\n");
    printf("Main\tIS   @\n");
    printf("\tLOC  Main\n");
    printf("\n");

    /* 遍历所有顶层节点 */
    for (int i = 0; i < program->child_count; i++) {
        ASTNode *child = program->children[i];
        if (child->type == ND_DECL) {
            int reg = symtab_lookup(symtab, child->name);
            printf("%% decl: int %s -> $%d\n", child->name, reg);
        } else {
            gen_statement(child);
        }
    }

    /* 程序结束 */
    printf("\n");
    emit_prefix();
    printf("TRAP 0,Halt,0\n");
}

/* ---- 语句生成 ---- */
static void gen_statement(ASTNode *node) {
    switch (node->type) {

    case ND_ASSIGN: {
        int reg = symtab_lookup(symtab, node->name);
        if (reg < 0) {
            fprintf(stderr, "Codegen error: undefined variable '%s'\n",
                    node->name);
            exit(1);
        }
        int src = gen_expr(node->rhs);
        if (src != reg) {
            emit_prefix();
            printf("SET $%d,$%d\n", reg, src);
        }
        break;
    }

    case ND_WHILE: {
        int lbl_start = new_label();
        int lbl_end   = new_label();

        /* 循环入口标签挂在第一条指令上 */
        set_label(lbl_start);

        /* 生成条件表达式 */
        int cond_reg = gen_expr(node->cond);

        /* 条件不满足则跳出 */
        emit_prefix();
        switch (last_cmp_op) {
            case OP_LE: printf("BP  $%d,L%d\n", cond_reg, lbl_end); break;
            case OP_LT: printf("BNN $%d,L%d\n", cond_reg, lbl_end); break;
            case OP_GE: printf("BN  $%d,L%d\n", cond_reg, lbl_end); break;
            case OP_GT: printf("BNP $%d,L%d\n", cond_reg, lbl_end); break;
            case OP_EQ: printf("BNZ $%d,L%d\n", cond_reg, lbl_end); break;
            case OP_NE: printf("BZ  $%d,L%d\n", cond_reg, lbl_end); break;
            default: break;
        }

        /* 循环体 */
        gen_statement(node->body);

        /* 跳回循环头 */
        emit_prefix();
        printf("JMP L%d\n", lbl_start);

        /* 循环出口标签挂在下一条指令上 */
        set_label(lbl_end);
        break;
    }

    case ND_BLOCK: {
        for (int i = 0; i < node->child_count; i++)
            gen_statement(node->children[i]);
        break;
    }

    default:
        fprintf(stderr, "Codegen error: unexpected statement type %d\n",
                node->type);
        exit(1);
    }
}

/* ---- 表达式生成，返回结果所在寄存器号 ---- */
static int gen_expr(ASTNode *node) {
    switch (node->type) {

    case ND_NUM: {
        int t = alloc_temp();
        emit_prefix();
        printf("SET $%d,%d\n", t, node->value);
        return t;
    }

    case ND_IDENT: {
        int reg = symtab_lookup(symtab, node->name);
        if (reg < 0) {
            fprintf(stderr, "Codegen error: undefined variable '%s'\n",
                    node->name);
            exit(1);
        }
        return reg;
    }

    case ND_BINOP: {
        int l = gen_expr(node->left);
        int r = gen_expr(node->right);
        int t = alloc_temp();

        emit_prefix();
        switch (node->op) {
            case OP_ADD: printf("ADD $%d,$%d,$%d\n", t, l, r); break;
            case OP_SUB: printf("SUB $%d,$%d,$%d\n", t, l, r); break;
            case OP_MUL: printf("MUL $%d,$%d,$%d\n", t, l, r); break;
            case OP_DIV: printf("DIV $%d,$%d,$%d\n", t, l, r); break;

            case OP_LT:
            case OP_GT:
            case OP_LE:
            case OP_GE:
            case OP_EQ:
            case OP_NE:
                printf("CMP $%d,$%d,$%d\n", t, l, r);
                last_cmp_op = node->op;
                break;
        }
        return t;
    }

    default:
        fprintf(stderr, "Codegen error: unexpected expr type %d\n",
                node->type);
        exit(1);
    }
}
