#include "gen.h"
#include "tokenbuf.h"
#include "lexer.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static SymTab   *symtab;
static int       label_seq;
static int       temp_seq;
static int       pending_label;
static BinOpType last_cmp_op;
static int       pos;          /* cursor into the token stream */

#define TEMP_BASE 200

static int new_label(void)  { return label_seq++; }
static int alloc_temp(void) { return TEMP_BASE + temp_seq++; }

static void set_label(int id) { pending_label = id; }

static void emit_prefix(void)
{
    if (pending_label >= 0) {
        printf("L%d\t", pending_label);
        pending_label = -1;
    } else {
        printf("\t");
    }
}

static void expect(TokenType type)
{
    Token *t = tokenbuf_get(pos);
    if (!t || t->type != type) {
        fprintf(stderr, "Error at token %d: expected %d, got %d ('%s')\n",
                pos, type, t ? t->type : -1, t ? t->text : "EOF");
        exit(1);
    }
    pos++;
}

/* ---- forward declarations ---- */
static void gen_statement(void);
static int  gen_expr(void);
static int  gen_comparison(void);
static int  gen_additive(void);
static int  gen_multiplicative(void);
static int  gen_primary(void);

/* =====================================================================
 * Entry point: skip declarations (already registered in symtab),
 * then walk statements and emit code directly.
 * ===================================================================== */
void generate(SymTab *st)
{
    symtab        = st;
    label_seq     = 0;
    temp_seq      = 0;
    pending_label = -1;
    pos           = 0;

    /* MMIX header */
    printf("%% Generated by JCC02M (no-AST)\n");
    printf("\tLOC  Data_Segment\n");
    printf("\tGREG @\n");
#ifdef JCC_MINI_DEBUG_PRET
    printf("DbgPfx\tBYTE\t\"ret = \",0\n");
    printf("DbgBuf\tBYTE\t0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n");
    printf("DbgNL\tBYTE\t10,0\n");
#endif
    printf("\tLOC  #100\n");
    printf("Main\tIS   @\n");
    printf("\tLOC  Main\n");
    printf("\n");

    /* Skip declaration tokens: int ident ; */
    while (tokenbuf_get(pos) && tokenbuf_get(pos)->type == TK_INT) {
        pos++; /* int  */
        pos++; /* ident */
        pos++; /* ;    */
    }

    /* Walk the rest of the token stream as statements */
    while (tokenbuf_get(pos) && tokenbuf_get(pos)->type != TK_EOF) {
        gen_statement();
    }

    printf("\n");

#ifdef JCC_MINI_DEBUG_PRET
    {
        int ret_reg = symtab_lookup(symtab, "ret");
        if (ret_reg >= 0) {
            int lbl_abs   = new_label();
            int lbl_loop  = new_label();
            int lbl_sign  = new_label();
            int lbl_add_sign = new_label();
            int lbl_out   = new_label();

            /* 输出 "ret = " */
            emit_prefix();
            printf("LDA $255,DbgPfx\n");
            emit_prefix();
            printf("TRAP 0,Fputs,StdOut\n");

            /* itoa: $250=buf, $251=pos, $252=num, $253=10, $249=sign_flag */
            emit_prefix();
            printf("LDA $250,DbgBuf\n");
            emit_prefix();
            printf("SET $251,24\n");
            emit_prefix();
            printf("SET $252,$%d\n", ret_reg);
            emit_prefix();
            printf("SET $253,10\n");
            emit_prefix();
            printf("SET $249,0\n");
            emit_prefix();
            printf("CMP $254,$252,0\n");
            emit_prefix();
            printf("BNN $254,L%d\n", lbl_abs);
            emit_prefix();
            printf("SET $249,1\n");
            emit_prefix();
            printf("NEG $252,$252\n");

            set_label(lbl_abs);
            emit_prefix();
            printf("PBNZ $252,L%d\n", lbl_loop);
            emit_prefix();
            printf("SET $254,'0'\n");
            emit_prefix();
            printf("STBU $254,$250,$251\n");
            emit_prefix();
            printf("JMP L%d\n", lbl_sign);

            set_label(lbl_loop);
            emit_prefix();
            printf("DIV $252,$252,$253\n");
            emit_prefix();
            printf("GET $254,rR\n");
            emit_prefix();
            printf("ADD $254,$254,'0'\n");
            emit_prefix();
            printf("STBU $254,$250,$251\n");
            emit_prefix();
            printf("SUB $251,$251,1\n");
            emit_prefix();
            printf("PBNZ $252,L%d\n", lbl_loop);
            emit_prefix();
            printf("ADD $251,$251,1\n");

            set_label(lbl_sign);
            emit_prefix();
            printf("PBNZ $249,L%d\n", lbl_add_sign);
            emit_prefix();
            printf("JMP L%d\n", lbl_out);

            set_label(lbl_add_sign);
            emit_prefix();
            printf("SUB $251,$251,1\n");
            emit_prefix();
            printf("SET $254,'-'\n");
            emit_prefix();
            printf("STBU $254,$250,$251\n");

            set_label(lbl_out);
            emit_prefix();
            printf("ADD $255,$250,$251\n");
            emit_prefix();
            printf("TRAP 0,Fputs,StdOut\n");

            /* 输出换行 */
            emit_prefix();
            printf("LDA $255,DbgNL\n");
            emit_prefix();
            printf("TRAP 0,Fputs,StdOut\n");
        }
    }
#endif

    emit_prefix();
    printf("TRAP 0,Halt,0\n");
}

/* =====================================================================
 * Statement → While | Block | Assignment
 * ===================================================================== */
static void gen_statement(void)
{
    Token *t = tokenbuf_get(pos);
    if (!t) return;

    /* ---- while ---- */
    if (t->type == TK_WHILE) {
        pos++;               /* consume 'while' */
        expect(TK_LPAREN);   /* consume '('       */

        int lbl_start = new_label();
        int lbl_end   = new_label();

        set_label(lbl_start);

        /* Condition expression */
        int cond_reg = gen_expr();
        expect(TK_RPAREN);   /* consume ')'       */

        /* Branch out if condition is false */
        emit_prefix();
        switch (last_cmp_op) {
            case OP_LE: printf("BP  $%d,L%d\n", cond_reg, lbl_end); break;
            case OP_LT: printf("BNN $%d,L%d\n", cond_reg, lbl_end); break;
            case OP_GE: printf("BN  $%d,L%d\n", cond_reg, lbl_end); break;
            case OP_GT: printf("BNP $%d,L%d\n", cond_reg, lbl_end); break;
            case OP_EQ: printf("BNZ $%d,L%d\n", cond_reg, lbl_end); break;
            case OP_NE: printf("BZ  $%d,L%d\n", cond_reg, lbl_end); break;
            default:    break;
        }

        /* Body (one statement, which may be a block) */
        gen_statement();

        emit_prefix();
        printf("JMP L%d\n", lbl_start);
        set_label(lbl_end);
        return;
    }

    /* ---- block ---- */
    if (t->type == TK_LBRACE) {
        pos++; /* consume '{' */
        while (tokenbuf_get(pos) &&
               tokenbuf_get(pos)->type != TK_RBRACE &&
               tokenbuf_get(pos)->type != TK_EOF) {
            gen_statement();
        }
        expect(TK_RBRACE); /* consume '}' */
        return;
    }

    /* ---- assignment ---- */
    {
        char name[64];
        strncpy(name, t->text, 63);
        pos++;               /* consume ident */
        expect(TK_ASSIGN);   /* consume '='   */

        int src = gen_expr();
        int reg = symtab_lookup(symtab, name);
        if (reg < 0) {
            fprintf(stderr, "Codegen error: undefined variable '%s'\n", name);
            exit(1);
        }
        if (src != reg) {
            emit_prefix();
            printf("SET $%d,$%d\n", reg, src);
        }
        expect(TK_SEMI);     /* consume ';'   */
    }
}

/* =====================================================================
 * Expression → Comparison → Additive → Multiplicative → Primary
 * ===================================================================== */
static int gen_expr(void)          { return gen_comparison(); }

static int gen_comparison(void)
{
    int left = gen_additive();
    Token *t = tokenbuf_get(pos);

    if (t && (t->type == TK_LT || t->type == TK_GT || t->type == TK_LE ||
              t->type == TK_GE || t->type == TK_EQ || t->type == TK_NE)) {
        BinOpType op;
        switch (t->type) {
            case TK_LT: op = OP_LT; break;
            case TK_GT: op = OP_GT; break;
            case TK_LE: op = OP_LE; break;
            case TK_GE: op = OP_GE; break;
            case TK_EQ: op = OP_EQ; break;
            case TK_NE: op = OP_NE; break;
            default:    op = OP_LT; break; /* unreachable */
        }
        pos++;
        int right = gen_additive();
        int treg  = alloc_temp();
        emit_prefix();
        printf("CMP $%d,$%d,$%d\n", treg, left, right);
        last_cmp_op = op;
        return treg;
    }
    return left;
}

static int gen_additive(void)
{
    int left = gen_multiplicative();
    Token *t = tokenbuf_get(pos);

    while (t && (t->type == TK_PLUS || t->type == TK_MINUS)) {
        int is_add = (t->type == TK_PLUS);
        pos++;
        int right = gen_multiplicative();
        int treg  = alloc_temp();
        emit_prefix();
        printf("%s $%d,$%d,$%d\n", is_add ? "ADD" : "SUB", treg, left, right);
        left = treg;
        t = tokenbuf_get(pos);
    }
    return left;
}

static int gen_multiplicative(void)
{
    int left = gen_primary();
    Token *t = tokenbuf_get(pos);

    while (t && (t->type == TK_MUL || t->type == TK_DIV)) {
        int is_mul = (t->type == TK_MUL);
        pos++;
        int right = gen_primary();
        int treg  = alloc_temp();
        emit_prefix();
        printf("%s $%d,$%d,$%d\n", is_mul ? "MUL" : "DIV", treg, left, right);
        left = treg;
        t = tokenbuf_get(pos);
    }
    return left;
}

static int gen_primary(void)
{
    Token *t = tokenbuf_get(pos);
    if (!t) {
        fprintf(stderr, "Codegen error: unexpected end of input\n");
        exit(1);
    }

    if (t->type == TK_IDENT) {
        pos++;
        int reg = symtab_lookup(symtab, t->text);
        if (reg < 0) {
            fprintf(stderr, "Codegen error: undefined variable '%s'\n", t->text);
            exit(1);
        }
        return reg;
    }

    if (t->type == TK_NUM) {
        pos++;
        int treg = alloc_temp();
        emit_prefix();
        printf("SET $%d,%d\n", treg, atoi(t->text));
        return treg;
    }

    if (t->type == TK_LPAREN) {
        pos++; /* consume '(' */
        int reg = gen_expr();
        expect(TK_RPAREN); /* consume ')' */
        return reg;
    }

    fprintf(stderr, "Codegen error: unexpected token '%s'\n", t->text);
    exit(1);
}
